# Generated by Django 4.2.5 on 2023-10-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile'),
        ),
    ]
