# Generated by Django 4.2.5 on 2023-11-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_baseuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller')], default='Customer', max_length=50),
        ),
    ]
